# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c3eb7abcf65aafee23d3cae9f23f88ad311212f65b30416b1abc6516b8e3c234c939f3d59e987ccb480cde7382d68fe2c86eb495e0a2e3b4e7de8ea690d07f

test:
  secret_key_base: 10a2569a77b2342d336f60597d1ae0e59f75362cde2aca21292bd98e741c2a5d97e404cf82c9661de80c75c03bb9d3ad1e277d9171623370830d0e5a92cf715e

development:
  secret_key_base: 62c3eb7abcf65aafee23d3cae9f23f88ad311212f65b30416b1abc6516b8e3c234c939f3d59e987ccb480cde7382d68fe2c86eb495e0a2e3b4e7de8ea690d07f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
